version: "3"
services:

  webserver:
    image: nginx:alpine
    container_name: alterapp-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "98:80"

  mariadb:
    image: mariadb:10.1
    container_name: alterapp-app-mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: alterapp-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - APP_ENV=dev
      - APP_SECRET=123i1o23i1n$$klasdasnd
      - DATABASE_URL=mysql://test:test@alterapp-app-mariadb:3306/test
      - MAILER_URL=smtp://alterapp-mailhog:1025

  composer:
    restart: 'no'
    container_name: alterapp-composer
    image: prooph/composer:7.2
    command: install
    volumes:
      - .:/application

  mailhog:
    image: mailhog/mailhog
    container_name: alterapp-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
